# Application Configuration
spring.application.name=fuel-tracker-backend

# Server Configuration
server.port=8080

# Logging Configuration
logging.level.root=INFO
logging.level.com.fueltracker=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Jackson Configuration
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null
